server: 
    port: ${SERVER_PORT:8761}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:discovery-server}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}

  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_CLIENTFETCH_REGISTRY:false}
    service-url:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/